package main

// fallbackModels：官方模型目录快照（含显示名），来源 command-code CLI
// 1.53.0 内置 command-code-knowledge/reference/models.md（由官方文档生成）。
// 仅当上游 /provider/v1/models 拉取失败时作回退；正常路径优先实时列表，
// 两条路径都会按套餐等级（plan_models.go 的 Min plan 表）过滤。
var fallbackModels = []modelInfo{
	{"deepseek/deepseek-v4-pro", "DeepSeek V4 Pro (latest)"},
	{"deepseek/deepseek-v4-flash", "DeepSeek V4 Flash (latest)"},
	{"deepseek/deepseek-v4-flash-vision-exp", "DeepSeek V4 Flash Vision (exp)"},
	{"deepseek/deepseek-v4-flash-fast", "DeepSeek V4 Flash Fast"},
	{"deepseek/deepseek-v4.1-flash", "DeepSeek V4.1 Flash"},
	{"moonshotai/Kimi-K3", "Kimi K3"},
	{"moonshotai/Kimi-K2.7-Code", "Kimi K2.7 Code"},
	{"moonshotai/Kimi-K2.7-Code-Highspeed", "Kimi K2.7 Code HighSpeed"},
	{"moonshotai/Kimi-K2.6", "Kimi K2.6"},
	{"moonshotai/Kimi-K2.5", "Kimi K2.5"},
	{"z-ai/glm-5.3-flash", "GLM-5.3 Flash"},
	{"zai-org/GLM-5.3", "GLM-5.3"},
	{"zai-org/GLM-5.2", "GLM-5.2"},
	{"zai-org/GLM-5.2-Fast", "GLM-5.2 Fast"},
	{"zai-org/GLM-5.1", "GLM-5.1"},
	{"zai-org/GLM-5", "GLM-5"},
	{"MiniMaxAI/MiniMax-M3", "MiniMax M3"},
	{"MiniMaxAI/MiniMax-M2.7", "MiniMax M2.7"},
	{"MiniMaxAI/MiniMax-M2.5", "MiniMax M2.5"},
	{"xiaomi/mimo-v2.5-pro", "MiMo V2.5 Pro"},
	{"xiaomi/mimo-v2.5", "MiMo V2.5"},
	{"Qwen/Qwen3.8-Max-0902", "Qwen 3.8 Max 0902"},
	{"Qwen/Qwen3.8-Max", "Qwen 3.8 Max"},
	{"Qwen/Qwen3.8-27B", "Qwen 3.8 27B"},
	{"Qwen/Qwen3.8-Flash", "Qwen 3.8 Flash"},
	{"Qwen/Qwen3.7-Max", "Qwen 3.7 Max"},
	{"Qwen/Qwen3.7-Plus", "Qwen 3.7 Plus"},
	{"Qwen/Qwen3.7-Flash", "Qwen 3.7 Flash"},
	{"Qwen/Qwen3.6-Max-Preview", "Qwen 3.6 Max Preview"},
	{"Qwen/Qwen3.6-Plus", "Qwen 3.6 Plus"},
	{"meituan/LongCat-2.0:free", "LongCat 2.0"},
	{"stepfun/Step-3.7-Flash", "Step 3.7 Flash"},
	{"stepfun/Step-3.5-Flash", "Step 3.5 Flash"},
	{"tencent/hy3-paid", "Tencent Hy3"},
	{"tencent/hy4-preview", "Tencent Hy4 Preview"},
	{"nvidia/nemotron-3-ultra-550b-a55b", "Nemotron 3 Ultra"},
	{"thinkingmachines/inkling", "Inkling"},
	{"thinkingmachines/inkling-small", "Inkling Small"},
	{"poolside/laguna-s-2.1-free", "Laguna S 2.1"},
	{"inclusionai/ling-3.0-flash-sante:free", "Ling 3.0 Flash Sante"},
	{"claude-sonnet-5", "Claude Sonnet 5"},
	{"claude-sonnet-4-6", "Claude Sonnet 4.6"},
	{"claude-fable-5-1", "Claude Fable 5.1"},
	{"claude-fable-5", "Claude Fable 5"},
	{"claude-opus-5", "Claude Opus 5"},
	{"claude-opus-4-8", "Claude Opus 4.8"},
	{"claude-opus-4-7", "Claude Opus 4.7"},
	{"claude-haiku-4-5-20251001", "Claude Haiku 4.5"},
	{"gpt-6-astra", "GPT-6 Astra"},
	{"gpt-5.6-sol", "GPT-5.6 Sol"},
	{"gpt-5.6-terra", "GPT-5.6 Terra"},
	{"gpt-5.6-luna", "GPT-5.6 Luna"},
	{"gpt-5.5", "GPT-5.5"},
	{"gpt-5.4", "GPT-5.4"},
	{"gpt-5.3-codex", "GPT-5.3 Codex"},
	{"gpt-5.4-mini", "GPT-5.4 Mini"},
	{"google/gemini-3.8-flash", "Gemini 3.8 Flash"},
	{"google/gemini-3.7-flash", "Gemini 3.7 Flash"},
	{"google/gemini-3.6-flash", "Gemini 3.6 Flash"},
	{"google/gemini-3.5-flash", "Gemini 3.5 Flash"},
	{"google/gemini-3.5-flash-lite", "Gemini 3.5 Flash Lite"},
	{"google/gemini-3.1-flash-lite", "Gemini 3.1 Flash Lite"},
	{"sakana/fugu-ultra", "Fugu Ultra"},
	{"meta/muse-spark-1.1", "Muse Spark 1.1"},
	{"meta/muse-spark-1.2", "Muse Spark 1.2"},
	{"meta/muse-spark-1.2-contributor", "Muse Spark 1.2 Contributor"},
	{"meta/muse-spark-1.3", "Muse Spark 1.3"},
	{"meta/muse-spark-1.3-contributor", "Muse Spark 1.3 Contributor"},
	{"xai/grok-4.5", "Grok 4.5"},
	{"xai/grok-4.6", "Grok 4.6"},
}
